sudo: false
language: go
go:
  - "1.9.5"
  - "1.9.6"
  - "1.9.7"
  - "1.10"
  - "1.10.1"
  - "1.10.2"
  - "1.10.3"
services:
  - redis-server
before_install:
  - go get -t -v ./...
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
script:
  - go test -coverprofile=ratelimiter.coverprofile
  - gover
  - goveralls -coverprofile=ratelimiter.coverprofile -service=travis-ci
